/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package dbmsdemo;
import java.sql.*;

/**
 *
 * @author J Mends
 */
public class frmAddClub extends javax.swing.JInternalFrame {
    private static final String DB_URL = "jdbc:mysql://localhost:3306/clubdatabase?useSSL=false&serverTimezone=UTC";
    private static final String USER = "root";
    private static final String PASSWORD = "root";
    /**
     * Creates new form frmAddClub
     */
    public frmAddClub() {
        initComponents();
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        createClubLabel = new javax.swing.JLabel();
        clubLocationField = new javax.swing.JTextField();
        whereMeetingLabel = new javax.swing.JLabel();
        clubNameField = new javax.swing.JTextField();
        nameClubLabel = new javax.swing.JLabel();
        clubTimeField = new javax.swing.JTextField();
        clubTimeLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        clubDaysField = new javax.swing.JTextField();
        createclubclosebtn = new javax.swing.JButton();

        createClubLabel.setText("Create Club");

        clubLocationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clubLocationFieldActionPerformed(evt);
            }
        });

        whereMeetingLabel.setText("Where will the club be meeting?");

        clubNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clubNameFieldActionPerformed(evt);
            }
        });

        nameClubLabel.setText("What is the name of the club?");

        clubTimeLabel.setText("What time will the club be meeting?");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("What days (Monday, Tuesday, etc..) will the club be meeting?");

        clubDaysField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clubDaysFieldActionPerformed(evt);
            }
        });

        createclubclosebtn.setText("Close");
        createclubclosebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createclubclosebtnActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(createClubLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(clubLocationField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(whereMeetingLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(clubNameField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(nameClubLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(clubTimeField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(clubTimeLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(submitButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(clubDaysField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(createclubclosebtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(createClubLabel)
                                .addComponent(whereMeetingLabel)
                                .addComponent(clubLocationField)
                                .addComponent(clubNameField)
                                .addComponent(nameClubLabel)
                                .addComponent(clubTimeField, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                            .addComponent(clubTimeLabel)
                            .addComponent(jLabel1)
                            .addComponent(clubDaysField, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(239, Short.MAX_VALUE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(submitButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createclubclosebtn)
                        .addGap(202, 202, 202))))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createClubLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameClubLabel)
                .addGap(3, 3, 3)
                .addComponent(clubNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clubDaysField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(whereMeetingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clubLocationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clubTimeLabel)
                .addGap(1, 1, 1)
                .addComponent(clubTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(submitButton)
                        .addContainerGap(149, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(createclubclosebtn)
                        .addGap(111, 111, 111))))
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clubLocationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clubLocationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clubLocationFieldActionPerformed

    private void clubNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clubNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clubNameFieldActionPerformed

    private void clubDaysFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clubDaysFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clubDaysFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitButtonActionPerformed

    private void createclubclosebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createclubclosebtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_createclubclosebtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JTextField clubDaysField;
    private javax.swing.JTextField clubLocationField;
    private javax.swing.JTextField clubNameField;
    private javax.swing.JTextField clubTimeField;
    private javax.swing.JLabel clubTimeLabel;
    private javax.swing.JLabel createClubLabel;
    private javax.swing.JButton createclubclosebtn;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nameClubLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel whereMeetingLabel;
    // End of variables declaration//GEN-END:variables
}
