/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package dbmsdemo;

/**
 *
 * @author J Mends
 */
public class frmAddClub extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmAddClub
     */
    public frmAddClub() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        createClubLabel = new javax.swing.JLabel();
        checkboxMonday = new javax.swing.JCheckBox();
        checkboxTuesday = new javax.swing.JCheckBox();
        checkboxWednesday = new javax.swing.JCheckBox();
        checkboxThursday = new javax.swing.JCheckBox();
        checkboxFriday = new javax.swing.JCheckBox();
        selectClubLabel = new javax.swing.JLabel();
        clubLocationField = new javax.swing.JTextField();
        whereMeetingLabel = new javax.swing.JLabel();
        clubNameField = new javax.swing.JTextField();
        nameClubLabel = new javax.swing.JLabel();
        clubTimeField = new javax.swing.JTextField();
        clubTimeLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();

        createClubLabel.setText("Create Club");

        checkboxMonday.setText("Monday");

        checkboxTuesday.setText("Tuesday");

        checkboxWednesday.setText("Wednesday");

        checkboxThursday.setText("Thursday");

        checkboxFriday.setText("Friday");

        selectClubLabel.setText("Select the club meeting day(s)");

        clubLocationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clubLocationFieldActionPerformed(evt);
            }
        });

        whereMeetingLabel.setText("Where will the club be meeting?");

        clubNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clubNameFieldActionPerformed(evt);
            }
        });

        nameClubLabel.setText("What is the name of the club?");

        clubTimeLabel.setText("What time will the club be meeting?");

        submitButton.setText("Submit");

        jDesktopPane1.setLayer(createClubLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(checkboxMonday, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(checkboxTuesday, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(checkboxWednesday, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(checkboxThursday, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(checkboxFriday, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(selectClubLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(clubLocationField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(whereMeetingLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(clubNameField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(nameClubLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(clubTimeField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(clubTimeLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(submitButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(createClubLabel)
                        .addComponent(checkboxMonday)
                        .addComponent(checkboxTuesday)
                        .addComponent(checkboxWednesday)
                        .addComponent(checkboxThursday)
                        .addComponent(checkboxFriday)
                        .addComponent(selectClubLabel)
                        .addComponent(whereMeetingLabel)
                        .addComponent(clubLocationField)
                        .addComponent(clubNameField)
                        .addComponent(nameClubLabel)
                        .addComponent(clubTimeField, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                    .addComponent(clubTimeLabel)
                    .addComponent(submitButton))
                .addContainerGap(359, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createClubLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameClubLabel)
                .addGap(3, 3, 3)
                .addComponent(clubNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selectClubLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkboxMonday)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkboxTuesday)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkboxWednesday)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkboxThursday)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkboxFriday)
                .addGap(22, 22, 22)
                .addComponent(whereMeetingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clubLocationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clubTimeLabel)
                .addGap(1, 1, 1)
                .addComponent(clubTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitButton)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clubLocationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clubLocationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clubLocationFieldActionPerformed

    private void clubNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clubNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clubNameFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JCheckBox checkboxFriday;
    private javax.swing.JCheckBox checkboxMonday;
    private javax.swing.JCheckBox checkboxThursday;
    private javax.swing.JCheckBox checkboxTuesday;
    private javax.swing.JCheckBox checkboxWednesday;
    private javax.swing.JTextField clubLocationField;
    private javax.swing.JTextField clubNameField;
    private javax.swing.JTextField clubTimeField;
    private javax.swing.JLabel clubTimeLabel;
    private javax.swing.JLabel createClubLabel;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel nameClubLabel;
    private javax.swing.JLabel selectClubLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel whereMeetingLabel;
    // End of variables declaration//GEN-END:variables
}
