/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbmsdemo;
import dbmsdemo.*;
//import dbmsdemo.frmViewUsers;
import java.awt.Toolkit;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JInternalFrame;


/**
 *
 * @author J Mends
 */
public class frmMain extends javax.swing.JFrame {

    frmLogin frmLogin = new frmLogin();
    frmAddAnnouncement frmAddAnnouncement = new frmAddAnnouncement();
    frmAddEvent frmAddEvent = new frmAddEvent();
    frmAddClub frmAddClub = new frmAddClub();
    frmRegisterUser frmRegisterUser = new frmRegisterUser();
    frmViewAnnouncement frmViewAnnouncement = new frmViewAnnouncement();
    frmViewClub frmViewClub = new frmViewClub();
    frmViewEvent frmViewEvent = new frmViewEvent();
    Map<String,JInternalFrame> forms = new HashMap<>();
    
    /**
     * Creates new form frmMain
     */
    public frmMain(){
        initComponents();
        forms.put("frmLogin", frmLogin);
        forms.put("frmAddAnnouncement", frmAddAnnouncement);
        forms.put("frmAddEvent", frmAddEvent);
        forms.put("frmAddClub", frmAddClub);
        forms.put("frmRegisterUser", frmRegisterUser);
        forms.put("frmViewAnnouncements", frmViewAnnouncement);
        forms.put("frmViewEvent", frmViewEvent);
        forms.put("frmViewClub", frmViewClub);
        
        
     forms.values().forEach((frm) ->{
         jdpContainer.add(frm);
     });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpContainer = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mniLogin = new javax.swing.JMenuItem();
        mniLogout = new javax.swing.JMenuItem();
        mniRegisterUser = new javax.swing.JCheckBoxMenuItem();
        mniExit = new javax.swing.JMenuItem();
        mnuView = new javax.swing.JMenu();
        mniViewClub = new javax.swing.JMenuItem();
        mniViewAnnouncement = new javax.swing.JMenuItem();
        mniViewEvent = new javax.swing.JMenuItem();
        mniViewUsers = new javax.swing.JMenuItem();
        mnuSearch = new javax.swing.JMenu();
        mniSearchClub = new javax.swing.JMenuItem();
        mnuCreate = new javax.swing.JMenu();
        mniCreateClub = new javax.swing.JMenuItem();
        mniCreateAnnouncement = new javax.swing.JMenuItem();
        mniCreateEvents = new javax.swing.JMenuItem();
        mnuManage = new javax.swing.JMenu();
        mniManageClub = new javax.swing.JMenuItem();
        mniManageAnnouncements = new javax.swing.JMenuItem();
        mniManageEvents = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdpContainer.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jdpContainer, java.awt.BorderLayout.CENTER);

        mnuFile.setText("File");

        mniLogin.setText("Login..");
        mniLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLoginActionPerformed(evt);
            }
        });
        mnuFile.add(mniLogin);

        mniLogout.setText("Logout");
        mnuFile.add(mniLogout);

        mniRegisterUser.setSelected(true);
        mniRegisterUser.setText("Register User ");
        mniRegisterUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniRegisterUserActionPerformed(evt);
            }
        });
        mnuFile.add(mniRegisterUser);

        mniExit.setText("Exit");
        mniExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExitActionPerformed(evt);
            }
        });
        mnuFile.add(mniExit);

        jMenuBar1.add(mnuFile);

        mnuView.setText("View");

        mniViewClub.setText("Club");
        mniViewClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniViewClubActionPerformed(evt);
            }
        });
        mnuView.add(mniViewClub);

        mniViewAnnouncement.setText("Announcements");
        mniViewAnnouncement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniViewAnnouncementActionPerformed(evt);
            }
        });
        mnuView.add(mniViewAnnouncement);

        mniViewEvent.setText("Events");
        mniViewEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniViewEventActionPerformed(evt);
            }
        });
        mnuView.add(mniViewEvent);

        mniViewUsers.setText("Users");
        mniViewUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniViewUsersActionPerformed(evt);
            }
        });
        mnuView.add(mniViewUsers);

        jMenuBar1.add(mnuView);

        mnuSearch.setText("Search");

        mniSearchClub.setText("Club");
        mnuSearch.add(mniSearchClub);

        jMenuBar1.add(mnuSearch);

        mnuCreate.setText("Create");

        mniCreateClub.setText("Club");
        mniCreateClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCreateClubActionPerformed(evt);
            }
        });
        mnuCreate.add(mniCreateClub);

        mniCreateAnnouncement.setText("Announcements");
        mniCreateAnnouncement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCreateAnnouncementActionPerformed(evt);
            }
        });
        mnuCreate.add(mniCreateAnnouncement);

        mniCreateEvents.setText("Events");
        mniCreateEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCreateEventsActionPerformed(evt);
            }
        });
        mnuCreate.add(mniCreateEvents);

        jMenuBar1.add(mnuCreate);

        mnuManage.setText("Manage");

        mniManageClub.setText("Club");
        mniManageClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniManageClubActionPerformed(evt);
            }
        });
        mnuManage.add(mniManageClub);

        mniManageAnnouncements.setText("Announcements");
        mniManageAnnouncements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniManageAnnouncementsActionPerformed(evt);
            }
        });
        mnuManage.add(mniManageAnnouncements);

        mniManageEvents.setText("Events");
        mnuManage.add(mniManageEvents);

        jMenuBar1.add(mnuManage);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLoginActionPerformed
        // TODO add your handling code here:
//        frmLogin frmLogin = new frmLogin();
        frmLogin.setVisible(true);
    }//GEN-LAST:event_mniLoginActionPerformed

    private void mniRegisterUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniRegisterUserActionPerformed
        // TODO add your handling code here:
        frmRegisterUser.setVisible(true);
    }//GEN-LAST:event_mniRegisterUserActionPerformed

    private void mniExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_mniExitActionPerformed

    private void mniViewUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniViewUsersActionPerformed
        // TODO add your handling code here:
        frmViewUsers frmViewUsers = new frmViewUsers();
        frmViewUsers.setVisible(true);
    }//GEN-LAST:event_mniViewUsersActionPerformed

    private void mniCreateClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCreateClubActionPerformed
        // TODO add your handling code here:
        frmAddClub.setVisible(true);
    }//GEN-LAST:event_mniCreateClubActionPerformed

    private void mniCreateAnnouncementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCreateAnnouncementActionPerformed
        // TODO add your handling code here:
        frmAddAnnouncement.setVisible(true);
    }//GEN-LAST:event_mniCreateAnnouncementActionPerformed

    private void mniCreateEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCreateEventsActionPerformed
        // TODO add your handling code here:
        frmAddEvent.setVisible(true);
    }//GEN-LAST:event_mniCreateEventsActionPerformed

    private void mniViewClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniViewClubActionPerformed
        // TODO add your handling code here:
        frmViewClub.setVisible(true);
    }//GEN-LAST:event_mniViewClubActionPerformed

    private void mniViewEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniViewEventActionPerformed
        // TODO add your handling code here:
        frmViewEvent.setVisible(true);
    }//GEN-LAST:event_mniViewEventActionPerformed

    private void mniViewAnnouncementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniViewAnnouncementActionPerformed
        // TODO add your handling code here:
        frmViewAnnouncement.setVisible(true);
    }//GEN-LAST:event_mniViewAnnouncementActionPerformed

    private void mniManageAnnouncementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniManageAnnouncementsActionPerformed
        // TODO add your handling code here:
        frmManageAnnouncement manageAnnouncement = new frmManageAnnouncement();
        manageAnnouncement.setVisible(true);
    }//GEN-LAST:event_mniManageAnnouncementsActionPerformed

    private void mniManageClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniManageClubActionPerformed
        // TODO add your handling code here:
        //frmManageClub.setVisible(true);
    }//GEN-LAST:event_mniManageClubActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmMain frmMain = new frmMain();
                frmMain.setSize(Toolkit.getDefaultToolkit().getScreenSize());
                frmMain.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdpContainer;
    private javax.swing.JMenuItem mniCreateAnnouncement;
    private javax.swing.JMenuItem mniCreateClub;
    private javax.swing.JMenuItem mniCreateEvents;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mniLogin;
    private javax.swing.JMenuItem mniLogout;
    private javax.swing.JMenuItem mniManageAnnouncements;
    private javax.swing.JMenuItem mniManageClub;
    private javax.swing.JMenuItem mniManageEvents;
    private javax.swing.JCheckBoxMenuItem mniRegisterUser;
    private javax.swing.JMenuItem mniSearchClub;
    private javax.swing.JMenuItem mniViewAnnouncement;
    private javax.swing.JMenuItem mniViewClub;
    private javax.swing.JMenuItem mniViewEvent;
    private javax.swing.JMenuItem mniViewUsers;
    private javax.swing.JMenu mnuCreate;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuManage;
    private javax.swing.JMenu mnuSearch;
    private javax.swing.JMenu mnuView;
    // End of variables declaration//GEN-END:variables
}
