/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package dbmsdemo;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;




/**
 *
 * @author kligs
 */
public class frmRegisterUser extends javax.swing.JInternalFrame {
    private static final String DB_URL = "jdbc:mysql://127.0.0.1:3306/clubdatabase?useSSL=false&serverTimezone=UTC";
    private static final String USER = "root";
    private static final String PASSWORD = "root";
    /**
     * Creates new form FormRegisterUser
     */
    public frmRegisterUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        nameField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        phoneLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        registerNewUserLabel = new javax.swing.JLabel();
        registerConfirmationButton = new javax.swing.JButton();
        registerClosebtn = new javax.swing.JButton();
        adminBtn = new javax.swing.JRadioButton();

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        nameLabel.setText("Name");

        emailLabel.setText("Email");

        phoneLabel.setText("Phone Number");

        idLabel.setText("School ID");

        passwordLabel.setText("Password");

        registerNewUserLabel.setText("Register New User");

        registerConfirmationButton.setText("Enter");
        registerConfirmationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerConfirmationButtonActionPerformed(evt);
            }
        });

        registerClosebtn.setText("Close");
        registerClosebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerClosebtnActionPerformed(evt);
            }
        });

        adminBtn.setText("admin");

        jDesktopPane1.setLayer(nameField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(nameLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(emailField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(emailLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(phoneField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(phoneLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(idLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(passwordLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(idField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(passwordField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(registerNewUserLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(registerConfirmationButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(registerClosebtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(adminBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(registerNewUserLabel)
                        .addGap(204, 204, 204))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(registerConfirmationButton)
                                .addGap(83, 83, 83)
                                .addComponent(registerClosebtn)
                                .addGap(53, 53, 53)
                                .addComponent(adminBtn))
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(idLabel)
                                .addComponent(emailLabel)
                                .addComponent(nameField)
                                .addComponent(emailField)
                                .addComponent(idField)
                                .addComponent(passwordLabel)
                                .addComponent(phoneLabel)
                                .addComponent(phoneField)
                                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(81, Short.MAX_VALUE))))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(registerNewUserLabel)
                        .addGap(20, 20, 20))
                    .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(phoneLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerConfirmationButton)
                    .addComponent(registerClosebtn)
                    .addComponent(adminBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void registerClosebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerClosebtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_registerClosebtnActionPerformed

    private void registerUser(){
        String name = nameField.getText();
        String email = emailField.getText();
        String phoneNumber = phoneField.getText();
        String schoolID = idField.getText();
        
        
        
    }
    private void registerConfirmationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerConfirmationButtonActionPerformed
        // TODO add your handling code here:
        Connection con;
        char[] passwordchar = passwordField.getPassword();
        String password = new String(passwordchar);
        int schoolID = Integer.parseInt(idField.getText());
        try {
            if(adminBtn.isSelected()){
               con = DriverManager.getConnection(DB_URL,USER,PASSWORD);
               PreparedStatement st = con.prepareStatement("INSERT INTO User(schoolId,email,name,phoneNumber,password)values(?,?,?,?,?)");
            
                st.setInt(1,Integer.parseInt(idField.getText()));
                st.setString(2,emailField.getText());
                st.setString(3,nameField.getText());
                st.setString(4, phoneField.getText());
                st.setString(5,password);
                st.executeUpdate();
                
                PreparedStatement adminSt = con.prepareStatement("INSERT INTO Admin(schoolId)values(?)");
                adminSt.setInt(1,schoolID);
                adminSt.executeUpdate();
                
                st.close();
                adminSt.close();
                
            } else{
                con = DriverManager.getConnection(DB_URL,USER,PASSWORD);
                PreparedStatement st = con.prepareStatement("INSERT INTO User(schoolId,email,name,phoneNumber,password)values(?,?,?,?,?)");
            
                st.setInt(1,schoolID);
                st.setString(2,emailField.getText());
                st.setString(3,nameField.getText());
                st.setString(4, phoneField.getText());
                st.setString(5,password);
                
                PreparedStatement memSt = con.prepareStatement("INSERT INTO Member(schoolId)values(?)");
                memSt.setInt(1, schoolID);
                memSt.executeUpdate();
                
                st.close();
                memSt.close();
                
            }
            
            con.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(frmRegisterUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_registerConfirmationButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adminBtn;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JButton registerClosebtn;
    private javax.swing.JButton registerConfirmationButton;
    private javax.swing.JLabel registerNewUserLabel;
    // End of variables declaration//GEN-END:variables
}
